- name: Configure the ubuntu VMs
  hosts: lab
  become: true
  roles:
    - role: common
      vars:
        baseDomain: "{{ baseDomain | default(lookup('env','BASE_DOMAIN') | default('example.local')) }}"
